#!/bin/bash

# Insert a Google Maps API key into the index.html generated by Overviewer.
# Required for hosting on a webserver. Local viewing doesn't require this.

map_directory=$1
key=$2

if [ -z $map_directory ] || [ -z $key ];then
  echo "Usage: insert <map directory> <api key>"
  exit 1
fi

# add API key to index.html
sed -i "s/\?sensor=false/&\&key=${key}/g" ${map_directory}/index.html
